### ISSUE TITLE
Text won't draw each frame

### ISSUE THREAD

**Issue by sbarisic** [harddal/TextBuffer#1]
https://github.com/harddal/TextBuffer/blob/master/TextBuffer.cpp#L155

There's a bug here, the Sprite will not draw each frame but just when the buffer is dirty. That's why my code has a Draw method that calls Update. 

Simple fix
`if (Dirty) { Dirty = false; /* update stuf*/ } window.draw(Sprite);`

https://github.com/cartman300/SFMLTextBuffer/blob/master/TextBuffer.cs#L249-L252

**Comment by harddal** [comment]
Fixed, I added a separate draw method like you have.
